"""
Echo filtering — detect and skip streaming progress echoes, no-text fallback
echoes, and strip leading MXID prefixes from bridged messages.
"""

from src.matrix.letta_bridge import NO_TEXT_RESPONSE_FALLBACK

# Streaming progress patterns that should never be routed to agents.
# These are generated by StreamingMessageHandler / LiveEditStreamingHandler
# and echoed back via bridge rooms, causing feedback loops.
_STREAMING_PROGRESS_PREFIXES = (
    '🔧 ',   # 🔧 tool call
    '✅ ',       # ✅ tool success
    '❌ ',       # ❌ tool failure
    '💭 ',   # 💭 reasoning
    '⏳ ',       # ⏳ still processing / approval
    '⚠️ ',  # ⚠️ error
)


def _strip_leading_mxid_prefix(text: str) -> str:
    stripped = (text or '').strip()
    if not stripped.startswith('@'):
        return stripped
    first, *rest = stripped.split(None, 1)
    if ':' not in first:
        return stripped
    if not rest:
        return stripped
    return rest[0].strip()


def _is_streaming_progress(text: str) -> bool:
    stripped = _strip_leading_mxid_prefix(text)
    if not stripped:
        return False

    # Split into non-empty lines
    non_empty = [ln.strip() for ln in stripped.splitlines() if ln.strip()]
    if not non_empty:
        return False

    # ALL non-empty lines must start with a streaming progress prefix.
    return all(
        ln.startswith(_STREAMING_PROGRESS_PREFIXES) for ln in non_empty
    )


def _is_no_text_fallback_echo(text: str) -> bool:
    return _strip_leading_mxid_prefix(text) == NO_TEXT_RESPONSE_FALLBACK
